---
name: Sculptor-Date
version: 0.02
author:
  - 'Damon Allen Davison <allolex@cpan.org>'
abstract: Convert Sculptor 4GL dates
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Date::Calc: 0
configure_requires:
  Module::Build: 0.34
provides:
  Sculptor::Date:
    file: lib/Sculptor/Date.pm
    version: 0.02
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
